# Generated by Django 6.1 on 2026-08-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0002_alter_appointment_doctor_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consulation"),
                            ("CANCELLATION_FEE", "Cancellation_fee"),
                            ("NO_SHOW_FEE", "No_show_fee"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "session_url",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="appointment.appointment",
                    ),
                ),
            ],
        ),
    ]
