# Generated by Django 6.1 on 2026-09-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("CONSULTATION", "Consultation"),
                    ("CANCELLATION_FEE", "Cancellation_fee"),
                    ("NO_SHOW_FEE", "No_show_fee"),
                ],
                max_length=50,
            ),
        ),
    ]
