# Generated by Django 6.1 on 2026-08-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specializations_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="code",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
