# Generated by Django 6.1 on 2026-08-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
        (
            "doctors_and_slots_service",
            "0002_alter_doctorslot_end_alter_doctorslot_start",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors_and_slots_service.doctorslot",
            ),
        ),
    ]
