# Generated by Django 6.1 on 2026-08-27 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("specializations_service", "0002_alter_specialization_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "price_per_visit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "specializations",
                    models.ManyToManyField(to="specializations_service.specialization"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors_and_slots_service.doctor",
                    ),
                ),
            ],
        ),
    ]
