# Generated by Django 6.1 on 2026-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors_and_slots_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorslot",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="doctorslot",
            name="start",
            field=models.DateTimeField(),
        ),
    ]
